{"created": 1741486642.592793, "duration": 5.077065944671631, "exitcode": 1, "root": "/Users/joan/VSProjects/pyERP/tests", "environment": {}, "summary": {"error": 8, "total": 8, "collected": 8}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "database", "type": "Package"}]}, {"nodeid": "database/test_migrations.py", "outcome": "passed", "result": [{"nodeid": "database/test_migrations.py::test_migrations_are_in_sync", "type": "Function", "lineno": 12}, {"nodeid": "database/test_migrations.py::test_migrations_can_be_applied", "type": "Function", "lineno": 20}]}, {"nodeid": "database/test_models.py::TestImageSyncLog", "outcome": "passed", "result": [{"nodeid": "database/test_models.py::TestImageSyncLog::test_create_log", "type": "Function", "lineno": 17}]}, {"nodeid": "database/test_models.py::TestProductModels", "outcome": "passed", "result": [{"nodeid": "database/test_models.py::TestProductModels::test_parent_product_creation", "type": "Function", "lineno": 35}, {"nodeid": "database/test_models.py::TestProductModels::test_variant_product_creation", "type": "Function", "lineno": 46}, {"nodeid": "database/test_models.py::TestProductModels::test_variant_requires_parent", "type": "Function", "lineno": 62}]}, {"nodeid": "database/test_models.py", "outcome": "passed", "result": [{"nodeid": "database/test_models.py::TestImageSyncLog", "type": "Class"}, {"nodeid": "database/test_models.py::TestProductModels", "type": "Class"}]}, {"nodeid": "database/test_queries.py::TestProductQueries", "outcome": "passed", "result": [{"nodeid": "database/test_queries.py::TestProductQueries::test_parent_with_variants_count", "type": "Function", "lineno": 48}, {"nodeid": "database/test_queries.py::TestProductQueries::test_complex_product_query", "type": "Function", "lineno": 64}]}, {"nodeid": "database/test_queries.py", "outcome": "passed", "result": [{"nodeid": "database/test_queries.py::TestProductQueries", "type": "Class"}]}, {"nodeid": "database", "outcome": "passed", "result": [{"nodeid": "database/test_migrations.py", "type": "Module"}, {"nodeid": "database/test_models.py", "type": "Module"}, {"nodeid": "database/test_queries.py", "type": "Module"}]}], "tests": [{"nodeid": "database/test_migrations.py::test_migrations_are_in_sync", "lineno": 12, "outcome": "error", "keywords": ["test_migrations_are_in_sync", "django_db", "pytestmark", "test_migrations.py", "database", "tests", ""], "setup": {"duration": 0.1632737920153886, "outcome": "failed", "crash": {"path": "/Users/joan/VSProjects/pyERP/venv/lib/python3.12/site-packages/django/db/models/fields/__init__.py", "lineno": 2859, "message": "TypeError: issubclass() arg 1 must be a class"}, "traceback": [{"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/fixtures.py", "lineno": 139, "message": "in django_db_setup"}, {"path": "venv/lib/python3.12/site-packages/django/test/utils.py", "lineno": 206, "message": "in setup_databases"}, {"path": "venv/lib/python3.12/site-packages/django/db/backends/base/creation.py", "lineno": 78, "message": "in create_test_db"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/__init__.py", "lineno": 194, "message": "in call_command"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/base.py", "lineno": 459, "message": "in execute"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/base.py", "lineno": 107, "message": "in wrapper"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/commands/migrate.py", "lineno": 118, "message": "in handle"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/executor.py", "lineno": 18, "message": "in __init__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/loader.py", "lineno": 58, "message": "in __init__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/loader.py", "lineno": 235, "message": "in build_graph"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 89, "message": "in applied_migrations"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 66, "message": "in has_table"}, {"path": "venv/lib/python3.12/site-packages/django/utils/functional.py", "lineno": 61, "message": "in __get__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 32, "message": "in Migration"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/base.py", "lineno": 365, "message": "in __new__"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/base.py", "lineno": 378, "message": "in _prepare"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/options.py", "lineno": 318, "message": "in _prepare"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/options.py", "lineno": 271, "message": "in _get_default_pk_class"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/fields/__init__.py", "lineno": 2859, "message": "in __subclasscheck__"}], "stderr": "Creating test database for alias 'default' ('/Users/joan/VSProjects/pyERP/pyerp/test_db.sqlite3')...\nDestroying old test database for alias 'default' ('/Users/joan/VSProjects/pyERP/pyerp/test_db.sqlite3')...\n", "longrepr": "venv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/fixtures.py:139: in django_db_setup\n    db_cfg = setup_databases(\nvenv/lib/python3.12/site-packages/django/test/utils.py:206: in setup_databases\n    connection.creation.create_test_db(\nvenv/lib/python3.12/site-packages/django/db/backends/base/creation.py:78: in create_test_db\n    call_command(\nvenv/lib/python3.12/site-packages/django/core/management/__init__.py:194: in call_command\n    return command.execute(*args, **defaults)\nvenv/lib/python3.12/site-packages/django/core/management/base.py:459: in execute\n    output = self.handle(*args, **options)\nvenv/lib/python3.12/site-packages/django/core/management/base.py:107: in wrapper\n    res = handle_func(*args, **kwargs)\nvenv/lib/python3.12/site-packages/django/core/management/commands/migrate.py:118: in handle\n    executor = MigrationExecutor(connection, self.migration_progress_callback)\nvenv/lib/python3.12/site-packages/django/db/migrations/executor.py:18: in __init__\n    self.loader = MigrationLoader(self.connection)\nvenv/lib/python3.12/site-packages/django/db/migrations/loader.py:58: in __init__\n    self.build_graph()\nvenv/lib/python3.12/site-packages/django/db/migrations/loader.py:235: in build_graph\n    self.applied_migrations = recorder.applied_migrations()\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:89: in applied_migrations\n    if self.has_table():\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:66: in has_table\n    self._has_table = self.Migration._meta.db_table in tables\nvenv/lib/python3.12/site-packages/django/utils/functional.py:61: in __get__\n    return self.fget(cls)\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:32: in Migration\n    class Migration(models.Model):\nvenv/lib/python3.12/site-packages/django/db/models/base.py:365: in __new__\n    new_class._prepare()\nvenv/lib/python3.12/site-packages/django/db/models/base.py:378: in _prepare\n    opts._prepare(cls)\nvenv/lib/python3.12/site-packages/django/db/models/options.py:318: in _prepare\n    pk_class = self._get_default_pk_class()\nvenv/lib/python3.12/site-packages/django/db/models/options.py:271: in _get_default_pk_class\n    if not issubclass(pk_class, AutoField):\nvenv/lib/python3.12/site-packages/django/db/models/fields/__init__.py:2859: in __subclasscheck__\n    return issubclass(subclass, self._subclasses) or super().__subclasscheck__(\nE   TypeError: issubclass() arg 1 must be a class"}, "teardown": {"duration": 0.0005899579846300185, "outcome": "passed"}}, {"nodeid": "database/test_migrations.py::test_migrations_can_be_applied", "lineno": 20, "outcome": "error", "keywords": ["test_migrations_can_be_applied", "django_db", "pytestmark", "test_migrations.py", "database", "tests", ""], "setup": {"duration": 0.001022542011924088, "outcome": "failed", "crash": {"path": "/Users/joan/VSProjects/pyERP/venv/lib/python3.12/site-packages/django/db/models/fields/__init__.py", "lineno": 2859, "message": "TypeError: issubclass() arg 1 must be a class"}, "traceback": [{"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/fixtures.py", "lineno": 139, "message": "in django_db_setup"}, {"path": "venv/lib/python3.12/site-packages/django/test/utils.py", "lineno": 206, "message": "in setup_databases"}, {"path": "venv/lib/python3.12/site-packages/django/db/backends/base/creation.py", "lineno": 78, "message": "in create_test_db"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/__init__.py", "lineno": 194, "message": "in call_command"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/base.py", "lineno": 459, "message": "in execute"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/base.py", "lineno": 107, "message": "in wrapper"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/commands/migrate.py", "lineno": 118, "message": "in handle"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/executor.py", "lineno": 18, "message": "in __init__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/loader.py", "lineno": 58, "message": "in __init__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/loader.py", "lineno": 235, "message": "in build_graph"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 89, "message": "in applied_migrations"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 66, "message": "in has_table"}, {"path": "venv/lib/python3.12/site-packages/django/utils/functional.py", "lineno": 61, "message": "in __get__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 32, "message": "in Migration"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/base.py", "lineno": 365, "message": "in __new__"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/base.py", "lineno": 378, "message": "in _prepare"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/options.py", "lineno": 318, "message": "in _prepare"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/options.py", "lineno": 271, "message": "in _get_default_pk_class"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/fields/__init__.py", "lineno": 2859, "message": "in __subclasscheck__"}], "longrepr": "venv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/fixtures.py:139: in django_db_setup\n    db_cfg = setup_databases(\nvenv/lib/python3.12/site-packages/django/test/utils.py:206: in setup_databases\n    connection.creation.create_test_db(\nvenv/lib/python3.12/site-packages/django/db/backends/base/creation.py:78: in create_test_db\n    call_command(\nvenv/lib/python3.12/site-packages/django/core/management/__init__.py:194: in call_command\n    return command.execute(*args, **defaults)\nvenv/lib/python3.12/site-packages/django/core/management/base.py:459: in execute\n    output = self.handle(*args, **options)\nvenv/lib/python3.12/site-packages/django/core/management/base.py:107: in wrapper\n    res = handle_func(*args, **kwargs)\nvenv/lib/python3.12/site-packages/django/core/management/commands/migrate.py:118: in handle\n    executor = MigrationExecutor(connection, self.migration_progress_callback)\nvenv/lib/python3.12/site-packages/django/db/migrations/executor.py:18: in __init__\n    self.loader = MigrationLoader(self.connection)\nvenv/lib/python3.12/site-packages/django/db/migrations/loader.py:58: in __init__\n    self.build_graph()\nvenv/lib/python3.12/site-packages/django/db/migrations/loader.py:235: in build_graph\n    self.applied_migrations = recorder.applied_migrations()\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:89: in applied_migrations\n    if self.has_table():\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:66: in has_table\n    self._has_table = self.Migration._meta.db_table in tables\nvenv/lib/python3.12/site-packages/django/utils/functional.py:61: in __get__\n    return self.fget(cls)\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:32: in Migration\n    class Migration(models.Model):\nvenv/lib/python3.12/site-packages/django/db/models/base.py:365: in __new__\n    new_class._prepare()\nvenv/lib/python3.12/site-packages/django/db/models/base.py:378: in _prepare\n    opts._prepare(cls)\nvenv/lib/python3.12/site-packages/django/db/models/options.py:318: in _prepare\n    pk_class = self._get_default_pk_class()\nvenv/lib/python3.12/site-packages/django/db/models/options.py:271: in _get_default_pk_class\n    if not issubclass(pk_class, AutoField):\nvenv/lib/python3.12/site-packages/django/db/models/fields/__init__.py:2859: in __subclasscheck__\n    return issubclass(subclass, self._subclasses) or super().__subclasscheck__(\nE   TypeError: issubclass() arg 1 must be a class"}, "teardown": {"duration": 0.0005143749876879156, "outcome": "passed"}}, {"nodeid": "database/test_models.py::TestImageSyncLog::test_create_log", "lineno": 17, "outcome": "error", "keywords": ["test_create_log", "TestImageSyncLog", "django_db", "test_models.py", "database", "tests", ""], "setup": {"duration": 0.00119479198474437, "outcome": "failed", "crash": {"path": "/Users/joan/VSProjects/pyERP/venv/lib/python3.12/site-packages/django/db/models/fields/__init__.py", "lineno": 2859, "message": "TypeError: issubclass() arg 1 must be a class"}, "traceback": [{"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/fixtures.py", "lineno": 139, "message": "in django_db_setup"}, {"path": "venv/lib/python3.12/site-packages/django/test/utils.py", "lineno": 206, "message": "in setup_databases"}, {"path": "venv/lib/python3.12/site-packages/django/db/backends/base/creation.py", "lineno": 78, "message": "in create_test_db"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/__init__.py", "lineno": 194, "message": "in call_command"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/base.py", "lineno": 459, "message": "in execute"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/base.py", "lineno": 107, "message": "in wrapper"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/commands/migrate.py", "lineno": 118, "message": "in handle"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/executor.py", "lineno": 18, "message": "in __init__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/loader.py", "lineno": 58, "message": "in __init__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/loader.py", "lineno": 235, "message": "in build_graph"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 89, "message": "in applied_migrations"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 66, "message": "in has_table"}, {"path": "venv/lib/python3.12/site-packages/django/utils/functional.py", "lineno": 61, "message": "in __get__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 32, "message": "in Migration"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/base.py", "lineno": 365, "message": "in __new__"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/base.py", "lineno": 378, "message": "in _prepare"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/options.py", "lineno": 318, "message": "in _prepare"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/options.py", "lineno": 271, "message": "in _get_default_pk_class"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/fields/__init__.py", "lineno": 2859, "message": "in __subclasscheck__"}], "longrepr": "venv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/fixtures.py:139: in django_db_setup\n    db_cfg = setup_databases(\nvenv/lib/python3.12/site-packages/django/test/utils.py:206: in setup_databases\n    connection.creation.create_test_db(\nvenv/lib/python3.12/site-packages/django/db/backends/base/creation.py:78: in create_test_db\n    call_command(\nvenv/lib/python3.12/site-packages/django/core/management/__init__.py:194: in call_command\n    return command.execute(*args, **defaults)\nvenv/lib/python3.12/site-packages/django/core/management/base.py:459: in execute\n    output = self.handle(*args, **options)\nvenv/lib/python3.12/site-packages/django/core/management/base.py:107: in wrapper\n    res = handle_func(*args, **kwargs)\nvenv/lib/python3.12/site-packages/django/core/management/commands/migrate.py:118: in handle\n    executor = MigrationExecutor(connection, self.migration_progress_callback)\nvenv/lib/python3.12/site-packages/django/db/migrations/executor.py:18: in __init__\n    self.loader = MigrationLoader(self.connection)\nvenv/lib/python3.12/site-packages/django/db/migrations/loader.py:58: in __init__\n    self.build_graph()\nvenv/lib/python3.12/site-packages/django/db/migrations/loader.py:235: in build_graph\n    self.applied_migrations = recorder.applied_migrations()\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:89: in applied_migrations\n    if self.has_table():\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:66: in has_table\n    self._has_table = self.Migration._meta.db_table in tables\nvenv/lib/python3.12/site-packages/django/utils/functional.py:61: in __get__\n    return self.fget(cls)\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:32: in Migration\n    class Migration(models.Model):\nvenv/lib/python3.12/site-packages/django/db/models/base.py:365: in __new__\n    new_class._prepare()\nvenv/lib/python3.12/site-packages/django/db/models/base.py:378: in _prepare\n    opts._prepare(cls)\nvenv/lib/python3.12/site-packages/django/db/models/options.py:318: in _prepare\n    pk_class = self._get_default_pk_class()\nvenv/lib/python3.12/site-packages/django/db/models/options.py:271: in _get_default_pk_class\n    if not issubclass(pk_class, AutoField):\nvenv/lib/python3.12/site-packages/django/db/models/fields/__init__.py:2859: in __subclasscheck__\n    return issubclass(subclass, self._subclasses) or super().__subclasscheck__(\nE   TypeError: issubclass() arg 1 must be a class"}, "teardown": {"duration": 0.0006060000159777701, "outcome": "passed"}}, {"nodeid": "database/test_models.py::TestProductModels::test_parent_product_creation", "lineno": 35, "outcome": "error", "keywords": ["test_parent_product_creation", "TestProductModels", "django_db", "test_models.py", "database", "tests", ""], "setup": {"duration": 0.001493458985351026, "outcome": "failed", "crash": {"path": "/Users/joan/VSProjects/pyERP/venv/lib/python3.12/site-packages/django/db/models/fields/__init__.py", "lineno": 2859, "message": "TypeError: issubclass() arg 1 must be a class"}, "traceback": [{"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/fixtures.py", "lineno": 139, "message": "in django_db_setup"}, {"path": "venv/lib/python3.12/site-packages/django/test/utils.py", "lineno": 206, "message": "in setup_databases"}, {"path": "venv/lib/python3.12/site-packages/django/db/backends/base/creation.py", "lineno": 78, "message": "in create_test_db"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/__init__.py", "lineno": 194, "message": "in call_command"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/base.py", "lineno": 459, "message": "in execute"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/base.py", "lineno": 107, "message": "in wrapper"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/commands/migrate.py", "lineno": 118, "message": "in handle"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/executor.py", "lineno": 18, "message": "in __init__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/loader.py", "lineno": 58, "message": "in __init__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/loader.py", "lineno": 235, "message": "in build_graph"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 89, "message": "in applied_migrations"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 66, "message": "in has_table"}, {"path": "venv/lib/python3.12/site-packages/django/utils/functional.py", "lineno": 61, "message": "in __get__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 32, "message": "in Migration"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/base.py", "lineno": 365, "message": "in __new__"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/base.py", "lineno": 378, "message": "in _prepare"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/options.py", "lineno": 318, "message": "in _prepare"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/options.py", "lineno": 271, "message": "in _get_default_pk_class"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/fields/__init__.py", "lineno": 2859, "message": "in __subclasscheck__"}], "longrepr": "venv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/fixtures.py:139: in django_db_setup\n    db_cfg = setup_databases(\nvenv/lib/python3.12/site-packages/django/test/utils.py:206: in setup_databases\n    connection.creation.create_test_db(\nvenv/lib/python3.12/site-packages/django/db/backends/base/creation.py:78: in create_test_db\n    call_command(\nvenv/lib/python3.12/site-packages/django/core/management/__init__.py:194: in call_command\n    return command.execute(*args, **defaults)\nvenv/lib/python3.12/site-packages/django/core/management/base.py:459: in execute\n    output = self.handle(*args, **options)\nvenv/lib/python3.12/site-packages/django/core/management/base.py:107: in wrapper\n    res = handle_func(*args, **kwargs)\nvenv/lib/python3.12/site-packages/django/core/management/commands/migrate.py:118: in handle\n    executor = MigrationExecutor(connection, self.migration_progress_callback)\nvenv/lib/python3.12/site-packages/django/db/migrations/executor.py:18: in __init__\n    self.loader = MigrationLoader(self.connection)\nvenv/lib/python3.12/site-packages/django/db/migrations/loader.py:58: in __init__\n    self.build_graph()\nvenv/lib/python3.12/site-packages/django/db/migrations/loader.py:235: in build_graph\n    self.applied_migrations = recorder.applied_migrations()\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:89: in applied_migrations\n    if self.has_table():\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:66: in has_table\n    self._has_table = self.Migration._meta.db_table in tables\nvenv/lib/python3.12/site-packages/django/utils/functional.py:61: in __get__\n    return self.fget(cls)\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:32: in Migration\n    class Migration(models.Model):\nvenv/lib/python3.12/site-packages/django/db/models/base.py:365: in __new__\n    new_class._prepare()\nvenv/lib/python3.12/site-packages/django/db/models/base.py:378: in _prepare\n    opts._prepare(cls)\nvenv/lib/python3.12/site-packages/django/db/models/options.py:318: in _prepare\n    pk_class = self._get_default_pk_class()\nvenv/lib/python3.12/site-packages/django/db/models/options.py:271: in _get_default_pk_class\n    if not issubclass(pk_class, AutoField):\nvenv/lib/python3.12/site-packages/django/db/models/fields/__init__.py:2859: in __subclasscheck__\n    return issubclass(subclass, self._subclasses) or super().__subclasscheck__(\nE   TypeError: issubclass() arg 1 must be a class"}, "teardown": {"duration": 0.0005259159952402115, "outcome": "passed"}}, {"nodeid": "database/test_models.py::TestProductModels::test_variant_product_creation", "lineno": 46, "outcome": "error", "keywords": ["test_variant_product_creation", "TestProductModels", "django_db", "test_models.py", "database", "tests", ""], "setup": {"duration": 0.0016750000067986548, "outcome": "failed", "crash": {"path": "/Users/joan/VSProjects/pyERP/venv/lib/python3.12/site-packages/django/db/models/fields/__init__.py", "lineno": 2859, "message": "TypeError: issubclass() arg 1 must be a class"}, "traceback": [{"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/fixtures.py", "lineno": 139, "message": "in django_db_setup"}, {"path": "venv/lib/python3.12/site-packages/django/test/utils.py", "lineno": 206, "message": "in setup_databases"}, {"path": "venv/lib/python3.12/site-packages/django/db/backends/base/creation.py", "lineno": 78, "message": "in create_test_db"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/__init__.py", "lineno": 194, "message": "in call_command"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/base.py", "lineno": 459, "message": "in execute"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/base.py", "lineno": 107, "message": "in wrapper"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/commands/migrate.py", "lineno": 118, "message": "in handle"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/executor.py", "lineno": 18, "message": "in __init__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/loader.py", "lineno": 58, "message": "in __init__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/loader.py", "lineno": 235, "message": "in build_graph"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 89, "message": "in applied_migrations"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 66, "message": "in has_table"}, {"path": "venv/lib/python3.12/site-packages/django/utils/functional.py", "lineno": 61, "message": "in __get__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 32, "message": "in Migration"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/base.py", "lineno": 365, "message": "in __new__"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/base.py", "lineno": 378, "message": "in _prepare"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/options.py", "lineno": 318, "message": "in _prepare"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/options.py", "lineno": 271, "message": "in _get_default_pk_class"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/fields/__init__.py", "lineno": 2859, "message": "in __subclasscheck__"}], "longrepr": "venv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/fixtures.py:139: in django_db_setup\n    db_cfg = setup_databases(\nvenv/lib/python3.12/site-packages/django/test/utils.py:206: in setup_databases\n    connection.creation.create_test_db(\nvenv/lib/python3.12/site-packages/django/db/backends/base/creation.py:78: in create_test_db\n    call_command(\nvenv/lib/python3.12/site-packages/django/core/management/__init__.py:194: in call_command\n    return command.execute(*args, **defaults)\nvenv/lib/python3.12/site-packages/django/core/management/base.py:459: in execute\n    output = self.handle(*args, **options)\nvenv/lib/python3.12/site-packages/django/core/management/base.py:107: in wrapper\n    res = handle_func(*args, **kwargs)\nvenv/lib/python3.12/site-packages/django/core/management/commands/migrate.py:118: in handle\n    executor = MigrationExecutor(connection, self.migration_progress_callback)\nvenv/lib/python3.12/site-packages/django/db/migrations/executor.py:18: in __init__\n    self.loader = MigrationLoader(self.connection)\nvenv/lib/python3.12/site-packages/django/db/migrations/loader.py:58: in __init__\n    self.build_graph()\nvenv/lib/python3.12/site-packages/django/db/migrations/loader.py:235: in build_graph\n    self.applied_migrations = recorder.applied_migrations()\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:89: in applied_migrations\n    if self.has_table():\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:66: in has_table\n    self._has_table = self.Migration._meta.db_table in tables\nvenv/lib/python3.12/site-packages/django/utils/functional.py:61: in __get__\n    return self.fget(cls)\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:32: in Migration\n    class Migration(models.Model):\nvenv/lib/python3.12/site-packages/django/db/models/base.py:365: in __new__\n    new_class._prepare()\nvenv/lib/python3.12/site-packages/django/db/models/base.py:378: in _prepare\n    opts._prepare(cls)\nvenv/lib/python3.12/site-packages/django/db/models/options.py:318: in _prepare\n    pk_class = self._get_default_pk_class()\nvenv/lib/python3.12/site-packages/django/db/models/options.py:271: in _get_default_pk_class\n    if not issubclass(pk_class, AutoField):\nvenv/lib/python3.12/site-packages/django/db/models/fields/__init__.py:2859: in __subclasscheck__\n    return issubclass(subclass, self._subclasses) or super().__subclasscheck__(\nE   TypeError: issubclass() arg 1 must be a class"}, "teardown": {"duration": 0.0008645410125609487, "outcome": "passed"}}, {"nodeid": "database/test_models.py::TestProductModels::test_variant_requires_parent", "lineno": 62, "outcome": "error", "keywords": ["test_variant_requires_parent", "TestProductModels", "django_db", "test_models.py", "database", "tests", ""], "setup": {"duration": 0.003494667005725205, "outcome": "failed", "crash": {"path": "/Users/joan/VSProjects/pyERP/venv/lib/python3.12/site-packages/django/db/models/fields/__init__.py", "lineno": 2859, "message": "TypeError: issubclass() arg 1 must be a class"}, "traceback": [{"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/fixtures.py", "lineno": 139, "message": "in django_db_setup"}, {"path": "venv/lib/python3.12/site-packages/django/test/utils.py", "lineno": 206, "message": "in setup_databases"}, {"path": "venv/lib/python3.12/site-packages/django/db/backends/base/creation.py", "lineno": 78, "message": "in create_test_db"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/__init__.py", "lineno": 194, "message": "in call_command"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/base.py", "lineno": 459, "message": "in execute"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/base.py", "lineno": 107, "message": "in wrapper"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/commands/migrate.py", "lineno": 118, "message": "in handle"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/executor.py", "lineno": 18, "message": "in __init__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/loader.py", "lineno": 58, "message": "in __init__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/loader.py", "lineno": 235, "message": "in build_graph"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 89, "message": "in applied_migrations"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 66, "message": "in has_table"}, {"path": "venv/lib/python3.12/site-packages/django/utils/functional.py", "lineno": 61, "message": "in __get__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 32, "message": "in Migration"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/base.py", "lineno": 365, "message": "in __new__"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/base.py", "lineno": 378, "message": "in _prepare"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/options.py", "lineno": 318, "message": "in _prepare"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/options.py", "lineno": 271, "message": "in _get_default_pk_class"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/fields/__init__.py", "lineno": 2859, "message": "in __subclasscheck__"}], "longrepr": "venv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/fixtures.py:139: in django_db_setup\n    db_cfg = setup_databases(\nvenv/lib/python3.12/site-packages/django/test/utils.py:206: in setup_databases\n    connection.creation.create_test_db(\nvenv/lib/python3.12/site-packages/django/db/backends/base/creation.py:78: in create_test_db\n    call_command(\nvenv/lib/python3.12/site-packages/django/core/management/__init__.py:194: in call_command\n    return command.execute(*args, **defaults)\nvenv/lib/python3.12/site-packages/django/core/management/base.py:459: in execute\n    output = self.handle(*args, **options)\nvenv/lib/python3.12/site-packages/django/core/management/base.py:107: in wrapper\n    res = handle_func(*args, **kwargs)\nvenv/lib/python3.12/site-packages/django/core/management/commands/migrate.py:118: in handle\n    executor = MigrationExecutor(connection, self.migration_progress_callback)\nvenv/lib/python3.12/site-packages/django/db/migrations/executor.py:18: in __init__\n    self.loader = MigrationLoader(self.connection)\nvenv/lib/python3.12/site-packages/django/db/migrations/loader.py:58: in __init__\n    self.build_graph()\nvenv/lib/python3.12/site-packages/django/db/migrations/loader.py:235: in build_graph\n    self.applied_migrations = recorder.applied_migrations()\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:89: in applied_migrations\n    if self.has_table():\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:66: in has_table\n    self._has_table = self.Migration._meta.db_table in tables\nvenv/lib/python3.12/site-packages/django/utils/functional.py:61: in __get__\n    return self.fget(cls)\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:32: in Migration\n    class Migration(models.Model):\nvenv/lib/python3.12/site-packages/django/db/models/base.py:365: in __new__\n    new_class._prepare()\nvenv/lib/python3.12/site-packages/django/db/models/base.py:378: in _prepare\n    opts._prepare(cls)\nvenv/lib/python3.12/site-packages/django/db/models/options.py:318: in _prepare\n    pk_class = self._get_default_pk_class()\nvenv/lib/python3.12/site-packages/django/db/models/options.py:271: in _get_default_pk_class\n    if not issubclass(pk_class, AutoField):\nvenv/lib/python3.12/site-packages/django/db/models/fields/__init__.py:2859: in __subclasscheck__\n    return issubclass(subclass, self._subclasses) or super().__subclasscheck__(\nE   TypeError: issubclass() arg 1 must be a class"}, "teardown": {"duration": 0.0006497080030385405, "outcome": "passed"}}, {"nodeid": "database/test_queries.py::TestProductQueries::test_parent_with_variants_count", "lineno": 48, "outcome": "error", "keywords": ["test_parent_with_variants_count", "TestProductQueries", "django_db", "test_queries.py", "database", "tests", ""], "setup": {"duration": 0.0016801669844426215, "outcome": "failed", "crash": {"path": "/Users/joan/VSProjects/pyERP/venv/lib/python3.12/site-packages/django/db/models/fields/__init__.py", "lineno": 2859, "message": "TypeError: issubclass() arg 1 must be a class"}, "traceback": [{"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/fixtures.py", "lineno": 139, "message": "in django_db_setup"}, {"path": "venv/lib/python3.12/site-packages/django/test/utils.py", "lineno": 206, "message": "in setup_databases"}, {"path": "venv/lib/python3.12/site-packages/django/db/backends/base/creation.py", "lineno": 78, "message": "in create_test_db"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/__init__.py", "lineno": 194, "message": "in call_command"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/base.py", "lineno": 459, "message": "in execute"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/base.py", "lineno": 107, "message": "in wrapper"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/commands/migrate.py", "lineno": 118, "message": "in handle"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/executor.py", "lineno": 18, "message": "in __init__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/loader.py", "lineno": 58, "message": "in __init__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/loader.py", "lineno": 235, "message": "in build_graph"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 89, "message": "in applied_migrations"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 66, "message": "in has_table"}, {"path": "venv/lib/python3.12/site-packages/django/utils/functional.py", "lineno": 61, "message": "in __get__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 32, "message": "in Migration"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/base.py", "lineno": 365, "message": "in __new__"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/base.py", "lineno": 378, "message": "in _prepare"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/options.py", "lineno": 318, "message": "in _prepare"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/options.py", "lineno": 271, "message": "in _get_default_pk_class"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/fields/__init__.py", "lineno": 2859, "message": "in __subclasscheck__"}], "longrepr": "venv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/fixtures.py:139: in django_db_setup\n    db_cfg = setup_databases(\nvenv/lib/python3.12/site-packages/django/test/utils.py:206: in setup_databases\n    connection.creation.create_test_db(\nvenv/lib/python3.12/site-packages/django/db/backends/base/creation.py:78: in create_test_db\n    call_command(\nvenv/lib/python3.12/site-packages/django/core/management/__init__.py:194: in call_command\n    return command.execute(*args, **defaults)\nvenv/lib/python3.12/site-packages/django/core/management/base.py:459: in execute\n    output = self.handle(*args, **options)\nvenv/lib/python3.12/site-packages/django/core/management/base.py:107: in wrapper\n    res = handle_func(*args, **kwargs)\nvenv/lib/python3.12/site-packages/django/core/management/commands/migrate.py:118: in handle\n    executor = MigrationExecutor(connection, self.migration_progress_callback)\nvenv/lib/python3.12/site-packages/django/db/migrations/executor.py:18: in __init__\n    self.loader = MigrationLoader(self.connection)\nvenv/lib/python3.12/site-packages/django/db/migrations/loader.py:58: in __init__\n    self.build_graph()\nvenv/lib/python3.12/site-packages/django/db/migrations/loader.py:235: in build_graph\n    self.applied_migrations = recorder.applied_migrations()\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:89: in applied_migrations\n    if self.has_table():\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:66: in has_table\n    self._has_table = self.Migration._meta.db_table in tables\nvenv/lib/python3.12/site-packages/django/utils/functional.py:61: in __get__\n    return self.fget(cls)\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:32: in Migration\n    class Migration(models.Model):\nvenv/lib/python3.12/site-packages/django/db/models/base.py:365: in __new__\n    new_class._prepare()\nvenv/lib/python3.12/site-packages/django/db/models/base.py:378: in _prepare\n    opts._prepare(cls)\nvenv/lib/python3.12/site-packages/django/db/models/options.py:318: in _prepare\n    pk_class = self._get_default_pk_class()\nvenv/lib/python3.12/site-packages/django/db/models/options.py:271: in _get_default_pk_class\n    if not issubclass(pk_class, AutoField):\nvenv/lib/python3.12/site-packages/django/db/models/fields/__init__.py:2859: in __subclasscheck__\n    return issubclass(subclass, self._subclasses) or super().__subclasscheck__(\nE   TypeError: issubclass() arg 1 must be a class"}, "teardown": {"duration": 0.0005109999910928309, "outcome": "passed"}}, {"nodeid": "database/test_queries.py::TestProductQueries::test_complex_product_query", "lineno": 64, "outcome": "error", "keywords": ["test_complex_product_query", "TestProductQueries", "django_db", "test_queries.py", "database", "tests", ""], "setup": {"duration": 0.0013483749935403466, "outcome": "failed", "crash": {"path": "/Users/joan/VSProjects/pyERP/venv/lib/python3.12/site-packages/django/db/models/fields/__init__.py", "lineno": 2859, "message": "TypeError: issubclass() arg 1 must be a class"}, "traceback": [{"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/plugin.py", "lineno": 532, "message": "in _django_db_marker"}, {"path": "venv/lib/python3.12/site-packages/pytest_django/fixtures.py", "lineno": 139, "message": "in django_db_setup"}, {"path": "venv/lib/python3.12/site-packages/django/test/utils.py", "lineno": 206, "message": "in setup_databases"}, {"path": "venv/lib/python3.12/site-packages/django/db/backends/base/creation.py", "lineno": 78, "message": "in create_test_db"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/__init__.py", "lineno": 194, "message": "in call_command"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/base.py", "lineno": 459, "message": "in execute"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/base.py", "lineno": 107, "message": "in wrapper"}, {"path": "venv/lib/python3.12/site-packages/django/core/management/commands/migrate.py", "lineno": 118, "message": "in handle"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/executor.py", "lineno": 18, "message": "in __init__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/loader.py", "lineno": 58, "message": "in __init__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/loader.py", "lineno": 235, "message": "in build_graph"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 89, "message": "in applied_migrations"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 66, "message": "in has_table"}, {"path": "venv/lib/python3.12/site-packages/django/utils/functional.py", "lineno": 61, "message": "in __get__"}, {"path": "venv/lib/python3.12/site-packages/django/db/migrations/recorder.py", "lineno": 32, "message": "in Migration"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/base.py", "lineno": 365, "message": "in __new__"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/base.py", "lineno": 378, "message": "in _prepare"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/options.py", "lineno": 318, "message": "in _prepare"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/options.py", "lineno": 271, "message": "in _get_default_pk_class"}, {"path": "venv/lib/python3.12/site-packages/django/db/models/fields/__init__.py", "lineno": 2859, "message": "in __subclasscheck__"}], "longrepr": "venv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/plugin.py:532: in _django_db_marker\n    request.getfixturevalue(\"_django_db_helper\")\nvenv/lib/python3.12/site-packages/pytest_django/fixtures.py:139: in django_db_setup\n    db_cfg = setup_databases(\nvenv/lib/python3.12/site-packages/django/test/utils.py:206: in setup_databases\n    connection.creation.create_test_db(\nvenv/lib/python3.12/site-packages/django/db/backends/base/creation.py:78: in create_test_db\n    call_command(\nvenv/lib/python3.12/site-packages/django/core/management/__init__.py:194: in call_command\n    return command.execute(*args, **defaults)\nvenv/lib/python3.12/site-packages/django/core/management/base.py:459: in execute\n    output = self.handle(*args, **options)\nvenv/lib/python3.12/site-packages/django/core/management/base.py:107: in wrapper\n    res = handle_func(*args, **kwargs)\nvenv/lib/python3.12/site-packages/django/core/management/commands/migrate.py:118: in handle\n    executor = MigrationExecutor(connection, self.migration_progress_callback)\nvenv/lib/python3.12/site-packages/django/db/migrations/executor.py:18: in __init__\n    self.loader = MigrationLoader(self.connection)\nvenv/lib/python3.12/site-packages/django/db/migrations/loader.py:58: in __init__\n    self.build_graph()\nvenv/lib/python3.12/site-packages/django/db/migrations/loader.py:235: in build_graph\n    self.applied_migrations = recorder.applied_migrations()\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:89: in applied_migrations\n    if self.has_table():\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:66: in has_table\n    self._has_table = self.Migration._meta.db_table in tables\nvenv/lib/python3.12/site-packages/django/utils/functional.py:61: in __get__\n    return self.fget(cls)\nvenv/lib/python3.12/site-packages/django/db/migrations/recorder.py:32: in Migration\n    class Migration(models.Model):\nvenv/lib/python3.12/site-packages/django/db/models/base.py:365: in __new__\n    new_class._prepare()\nvenv/lib/python3.12/site-packages/django/db/models/base.py:378: in _prepare\n    opts._prepare(cls)\nvenv/lib/python3.12/site-packages/django/db/models/options.py:318: in _prepare\n    pk_class = self._get_default_pk_class()\nvenv/lib/python3.12/site-packages/django/db/models/options.py:271: in _get_default_pk_class\n    if not issubclass(pk_class, AutoField):\nvenv/lib/python3.12/site-packages/django/db/models/fields/__init__.py:2859: in __subclasscheck__\n    return issubclass(subclass, self._subclasses) or super().__subclasscheck__(\nE   TypeError: issubclass() arg 1 must be a class"}, "teardown": {"duration": 0.005031125008827075, "outcome": "passed"}}], "warnings": [{"message": "Unknown config option: env\n", "category": "PytestConfigWarning", "when": "config", "filename": "/Users/joan/VSProjects/pyERP/venv/lib/python3.12/site-packages/_pytest/config/__init__.py", "lineno": 1396}]}